// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Alert': typeof import("../src/components/core/Alert.vue")['default'],
    'PageLoading': typeof import("../src/components/core/PageLoading.vue")['default'],
    'SkeletonLoader': typeof import("../src/components/core/SkeletonLoader.vue")['default'],
    'Modal': typeof import("../src/components/core/modal/Modal.vue")['default'],
    'ModalBase': typeof import("../src/components/core/modal/ModalBase.vue")['default'],
    'NavigationInGameNavBar': typeof import("../src/components/navigation/InGameNavBar.vue")['default'],
    'NavigationNavBar': typeof import("../src/components/navigation/NavBar.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyAlert': typeof import("../src/components/core/Alert.vue")['default'],
    'LazyPageLoading': typeof import("../src/components/core/PageLoading.vue")['default'],
    'LazySkeletonLoader': typeof import("../src/components/core/SkeletonLoader.vue")['default'],
    'LazyModal': typeof import("../src/components/core/modal/Modal.vue")['default'],
    'LazyModalBase': typeof import("../src/components/core/modal/ModalBase.vue")['default'],
    'LazyNavigationInGameNavBar': typeof import("../src/components/navigation/InGameNavBar.vue")['default'],
    'LazyNavigationNavBar': typeof import("../src/components/navigation/NavBar.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const Alert: typeof import("../src/components/core/Alert.vue")['default']
export const PageLoading: typeof import("../src/components/core/PageLoading.vue")['default']
export const SkeletonLoader: typeof import("../src/components/core/SkeletonLoader.vue")['default']
export const Modal: typeof import("../src/components/core/modal/Modal.vue")['default']
export const ModalBase: typeof import("../src/components/core/modal/ModalBase.vue")['default']
export const NavigationInGameNavBar: typeof import("../src/components/navigation/InGameNavBar.vue")['default']
export const NavigationNavBar: typeof import("../src/components/navigation/NavBar.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyAlert: typeof import("../src/components/core/Alert.vue")['default']
export const LazyPageLoading: typeof import("../src/components/core/PageLoading.vue")['default']
export const LazySkeletonLoader: typeof import("../src/components/core/SkeletonLoader.vue")['default']
export const LazyModal: typeof import("../src/components/core/modal/Modal.vue")['default']
export const LazyModalBase: typeof import("../src/components/core/modal/ModalBase.vue")['default']
export const LazyNavigationInGameNavBar: typeof import("../src/components/navigation/InGameNavBar.vue")['default']
export const LazyNavigationNavBar: typeof import("../src/components/navigation/NavBar.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
